sudo: required
dist: xenial

install:
  - sudo apt-get install reprepro -y

script:
 - mkdir conf/ && wget https://raw.githubusercontent.com/debian-pm-tools/apt-repo-conf/master/conf/distributions -O conf/distributions
 - reprepro checkpool
 - reprepro check

deploy:
  provider: script
  skip_cleanup: true
  script: ./rsync_deploy.sh
